### ISSUE TITLE
Use ConversationAdd instead of ConversationForward in submit form

### ISSUE THREAD

**Issue by tophcodes** [unkso/forward-conversation#1]
I think this is the same issue you already encountered, but when trying to submit a forwarded conversation I receive the error `Invalid conversation input ID`.

So should send the forward form to the `ConversationAdd` controller instead until we find a solution.

**Comment by mcherwin** [comment]
Unclear why inherited `save` function redirects incorrectly back to itself even with correct usage of `HeaderUtil` in `ConversationForwardForm` handler.  However, referencing the `ConversationAdd` handler in the `conversationForward` template still works to perform the actual save operation on form content.
